
-- hs.hotkey.bind({"escape"}, "`", function()
-- end)
--
--
local iconAscii = [[ASCII:
............
.....J......
............
............
KL........HI
............
............
.F........G.
............
............
.D........C.
............
.A........B.
............
]]

local function onClick()
    -- hs.application.launchOrFocus('Slack')
    return function()
      hs.hid.capslock.toggle() 

      -- hs.alert.show("Pressed") 
    end
end

local menu = hs.menubar.new():setClickCallback(onClick()):setIcon(iconAscii)
